apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9153"
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: rhcl
    app.kubernetes.io/name: coredns
    app.kubernetes.io/version: rhcl-1.3
  name: kuadrant-coredns-metrics
  namespace: kuadrant-coredns
spec:
  ports:
  - name: metrics
    port: 9153
    targetPort: 9153
  selector:
    app.kubernetes.io/instance: rhcl
    app.kubernetes.io/name: coredns
    app.kubernetes.io/version: rhcl-1.3
