- name: Create default GatewayClass
  redhat.openshift.k8s:
    src: default-gatewayclass.yaml
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
- name: Create kuadrant-system namespace
  redhat.openshift.k8s:
    src: kuadrant-system-namespace.yaml
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
- name: Create gateway-system namespace
  redhat.openshift.k8s:
    src: gateway-system-namespace.yaml
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
- name: Create Connectivity Link Subscription
  redhat.openshift.k8s:
    src: cl-sub.yaml
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
- name: Get Connectivity Link subscription
  redhat.openshift.k8s:
    kind: Subscription
    api_version: operators.coreos.com/v1alpha1
    name: rhcl-operator
    namespace: openshift-operators
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
  register: cl_sub
  until: cl_sub.result.status.installplan.name is defined
  retries: 12
  delay: 10
- name: Approve InstallPlan
  shell: |
    oc patch installplan {{ cl_sub.result.status.installplan.name }} --namespace openshift-operators --type merge --patch '{"spec":{"approved":true}}' -s {{ openshift_api_url }} --token {{ openshift_token }} --insecure-skip-tls-verify=true
- name: Wait until Connectivity Link subscription is "Ready"
  redhat.openshift.k8s:
    kind: Subscription
    api_version: operators.coreos.com/v1alpha1
    name: rhcl-operator
    namespace: openshift-operators
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
  register: cl_sub
  until: cl_sub.result.status.state is defined and (cl_sub.result.status.state == 'AtLatestKnown' or cl_sub.result.status.state == 'UpgradeAvailable')
  retries: 12
  delay: 10
- name: Create Pull secret
  redhat.openshift.k8s:
    template: pull_secret.yaml.j2
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
