- name: Include OpenShift Common
  include_role:
    name: openshift/common
    public: true
  when: openshift_token is undefined
- name: Create Keycloak namspace 
  redhat.openshift.k8s:
    template: namespace.yaml.j2
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
- name: Check for existing Operator Group
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1
    kind: OperatorGroup
    namespace: "{{ keycloak_namespace }}"
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
  register: keycloak_operator_group
- name: Create Keycloak Operator Group
  redhat.openshift.k8s:
    template: operator-group.yaml.j2
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
  when: keycloak_operator_group.resources[0] is not defined
- name: Create Keycloak subscription
  redhat.openshift.k8s:
    template: keycloak-sub.yaml.j2
    namespace: "{{ keycloak_namespace }}"
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
- name: Wait until Keycloak subscription is "Ready"
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: rhbk-operator
    namespace: "{{ keycloak_namespace }}"
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
  register: keycloak_sub
  until: keycloak_sub.resources[0].status.state is defined and (keycloak_sub.resources[0].status.state == 'AtLatestKnown' or keycloak_sub.resources[0].status.state == 'UpgradeAvailable')
  retries: 12
  delay: 5
  ignore_errors: yes
- name: Wait for RHBK Operator deployment
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: rhbk-operator
    namespace: "{{ keycloak_namespace }}"
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
  register: rhbk_operator_deployment
  until: rhbk_operator_deployment.resources[0].status is defined and rhbk_operator_deployment.resources[0].status.readyReplicas is defined and rhbk_operator_deployment.resources[0].status.readyReplicas == 1
  retries: 12
  delay: 10
- name: Create Keycloak DB Secret
  redhat.openshift.k8s:
    template: keycloak-db-secret.yaml.j2
    namespace: "{{ keycloak_namespace }}"
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
- name: Deploy Postgres
  include_role:
    name: postgres
  vars:
    postgres_name: "postgres-{{ keycloak_name }}"
    postgres_namespace: "{{ keycloak_namespace }}"
    postgres_database: keycloak
  when: postgres_deployment.resources[0].status is undefined
- name: Check if there is already a Keycloak instance
  kubernetes.core.k8s_info:
    api_version: k8s.keycloak.org/v2alpha1
    kind: Keycloak
    name: "{{ keycloak_name }}"
    namespace: "{{ keycloak_namespace }}"
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
  register: keycloak
- name: Create Keycloak instance
  redhat.openshift.k8s:
    template: keycloak.yaml.j2
    namespace: "{{ keycloak_namespace }}"
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
  when: keycloak.resources[0].status.instances is undefined
- name: Check for Keycloak deployment
  kubernetes.core.k8s_info:
    api_version: v1
    kind: StatefulSet
    name: "{{ keycloak_name }}"
    namespace: "{{ keycloak_namespace }}"
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
  register: rhbk_deployment
  until: rhbk_deployment.resources[0].status.readyReplicas is defined and rhbk_deployment.resources[0].status.readyReplicas == 1
  retries: 12
  delay: 10
