- name: Provision OpenShift AI
  hosts: ai
  connection: local
  vars:
    ai_models_enabled:
      - granite-3-3-8b-instruct
      - granite-8b-code-instruct
      - stable-diffusion-xl-mixed
      - qwen-3-5-27b
  roles:
    - openshift/user-workload-monitoring
    - openshift/data-foundation
    - openshift/nvidia-gpu-nodes/aws
    - nvidia-gpu
    - openshift/nfd
    - openshift/kueue
    - connectivity-link
    - openshift/lws
    - openshift/cluster-observability
    - openshift/tempo
    - openshift/opentelemetry
    - openshift/ai-3
    - ai-models
    - mcp-gateway
