- name: Include openshift/common role
  include_role:
    name: openshift/common
    public: true
  when: openshift_token is undefined
- name: Create nvidia-gpu-operator namespace
  redhat.openshift.k8s:
    src: namespace.yaml
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
- name: Create Operator Group
  redhat.openshift.k8s:
    src: operator-group.yaml
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
- name: Get NVIDIA GPU Channel version
  shell: |
    oc get packagemanifest gpu-operator-certified -n openshift-marketplace -o jsonpath='{.status.defaultChannel}' -s {{ openshift_api_url }} --token {{ openshift_token }} --insecure-skip-tls-verify=true
  register: nvidia_gpu_channel
- name: Get NVIDIA GPU CSV
  shell: |
    oc get packagemanifests/gpu-operator-certified -n openshift-marketplace -o json -s {{ openshift_api_url }} --token {{ openshift_token }} --insecure-skip-tls-verify=true | jq -r '.status.channels[] | select(.name == "'{{ nvidia_gpu_channel.stdout }}'") | .currentCSV'
  register: nvidia_gpu_csv
- name: Create Nvidia GPU subscription
  redhat.openshift.k8s:
    template: nvidia-gpu-sub.yaml.j2
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
- name: Get InstallPlan name
  shell: |
    oc get installplan -n nvidia-gpu-operator -oname -s {{ openshift_api_url }} --token {{ openshift_token }} --insecure-skip-tls-verify=true
  register: nvidia_gpu_installplan
  until: nvidia_gpu_installplan.stdout != ""
  retries: 12
  delay: 5
- name: Patch InstallPlan
  shell: |
    oc patch {{ nvidia_gpu_installplan.stdout }} -n nvidia-gpu-operator --type merge --patch '{"spec":{"approved":true }}' -s {{ openshift_api_url }} --token {{ openshift_token }} --insecure-skip-tls-verify=true
- name: Wait until NVIDIA GPU subscription is "Ready"
  redhat.openshift.k8s:
    kind: Subscription
    api_version: operators.coreos.com/v1alpha1
    name: nvidia-gpu
    namespace: nvidia-gpu-operator
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
  register: nvidia_gpu_sub
  until: nvidia_gpu_sub.result.status.state is defined and (nvidia_gpu_sub.result.status.state == 'AtLatestKnown' or nvidia_gpu_sub.result.status.state == 'UpgradeAvailable')
  retries: 12
  delay: 5
  ignore_errors: yes
- name: Create ClusterPolicy
  redhat.openshift.k8s:
    src: cluster-policy.yaml
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
- name: Create DCGM configmap
  redhat.openshift.k8s:
    template: nvidia-dcgm-exporter-dashboard-configmap.yaml.j2
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
