spec:
  monitoring:
    managementState: Managed
    namespace: redhat-ods-monitoring
    alerting: {}
    metrics:
      replicas: 1
      resources:
        cpulimit: 500m
        cpurequest: 100m
        memorylimit: 512Mi
        memoryrequest: 256Mi
      storage:
        size: 5Gi
        retention: 90d
      exporters: {}
    traces:
      sampleRatio: '0.1'
      storage:
        backend: pv
        retention: 2160h
      exporters: {}
