apiVersion: v1
kind: Secret
metadata:
  name: maas-db-config
stringData:
  DB_CONNECTION_URL: "postgresql://postgres:postgres@postgres-maas.redhat-ods-applications.svc.cluster.local:5432/maas?sslmode=require"
type: Opaque
