apiVersion: v1
kind: Secret
metadata:
  name: maas-db-config
  namespace: redhat-ods-applications
stringData:
  DB_CONNECTION_URL: "postgresql://postgres:postgres@postgres:5432/postgres?sslmode=require"
type: Opaque
