apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    openshift.io/display-name: vLLM CPU ServingRuntime for KServe
  labels:
    opendatahub.io/dashboard: 'true'
  name: servingruntime-cpu-only
spec:
  annotations:
    prometheus.io/port: '8080'
    prometheus.io/path: '/metrics'
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: vLLM
  containers:
    - name: kserve-container
      image: quay.io/rh-aiservices-bu/vllm-cpu-openai-ubi9:0.3
      command:
        - python
        - -m
        - vllm.entrypoints.openai.api_server
      args:
        - "--port=8080"
        - "--model=/mnt/models"
        - "--served-model-name={{.Name}}"
      ports:
        - containerPort: 8080
          protocol: TCP
