apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
stringData:
  POSTGRES_DATABASE: keycloak
  POSTGRES_EXTERNAL_ADDRESS: postgres
  POSTGRES_EXTERNAL_PORT: "5432"
  USERNAME: postgres
  PASSWORD: postgres
