- name: Include OpenShift Common role
  include_role:
    name: openshift/common
    public: true
  when: openshift_token is undefined
- name: Create OpenShift Tempo namespace
  redhat.openshift.k8s:
    src: namespace.yaml
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
- name: Create OpenShift Tempo operator-group
  redhat.openshift.k8s:
    src: operator-group.yaml
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
- name: Create OpenShift Tempo subscription
  redhat.openshift.k8s:
    src: tempo-sub.yaml
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
- name: Wait until OpenShift Tempo subscription is "Ready"
  kubernetes.core.k8s_info:
    kind: Subscription
    api_version: operators.coreos.com/v1alpha1
    name: tempo
    namespace: openshift-tempo-operator
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
  register: tempo_sub
  until: tempo_sub.resources[0].status.state is defined and (tempo_sub.resources[0].status.state == 'AtLatestKnown' or tempo_sub.resources[0].status.state == 'UpgradeAvailable')
  retries: 12
  delay: 5
  ignore_errors: yes
- name: Wait for Tempo Operator Deployment
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Deployment
    name: tempo-operator-controller
    namespace: openshift-tempo-operator
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
  register: tempo_operator_deployment
  until: tempo_operator_deployment.resources[0].status.readyReplicas is defined and tempo_operator_deployment.resources[0].status.readyReplicas == 1
  retries: 12
  delay: 5
- name: Create Tempo namespace
  redhat.openshift.k8s:
    src: namespace-tempo.yaml
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
- name: Create S3 Storage (ODF)
  ansible.builtin.include_tasks:
    file: create_odf_bucket_claim.yaml
  when: s3_storage_provider == "ODF"
- name: Create S3 Storage (MinIO)
  ansible.builtin.include_tasks:
    file: create_minio_bucket.yaml
  when: s3_storage_provider == "MinIO"
- name: Create Tempo Secret
  redhat.openshift.k8s:
    template: tempo-secret.yaml.j2
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
- name: Create TempoStack
  redhat.openshift.k8s:
    src: tempostack.yaml
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
- name: Create TempoStack ClusterRoleBinding
  redhat.openshift.k8s:
    src: clusterrole-binding.yaml
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
