- name: Include OpenShift Common role
  include_role:
    name: openshift/common
    public: true
  when: openshift_token is undefined
- name: Create OpenShift Tempo namespace
  redhat.openshift.k8s:
    src: namespace.yaml
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
- name: Create OpenShift Tempo operator-group
  redhat.openshift.k8s:
    src: operator-group.yaml
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
- name: Create OpenShift Tempo subscription
  redhat.openshift.k8s:
    src: tempo-sub.yaml
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
- name: Wait until OpenShift Tempo subscription is "Ready"
  kubernetes.core.k8s_info:
    kind: Subscription
    api_version: operators.coreos.com/v1alpha1
    name: tempo
    namespace: openshift-tempo-operator
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
  register: tempo_sub
  until: tempo_sub.resources[0].status.state is defined and (tempo_sub.resources[0].status.state == 'AtLatestKnown' or tempo_sub.resources[0].status.state == 'UpgradeAvailable')
  retries: 12
  delay: 5
  ignore_errors: yes
- name: Create Tempo namespace
  redhat.openshift.k8s:
    src: namespace-tempo.yaml
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
- name: Create ODF ObjectBucketClaim
  redhat.openshift.k8s:
    src: tempostack-obc.yaml
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
- name: Wait until ODF ObjectBucketClaim is "Ready"
  kubernetes.core.k8s_info:
    kind: ObjectBucketClaim
    api_version: v1alpha1
    name: tempostack-obc
    namespace: tempo
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
  register: tempostack_obc
  until: tempostack_obc.resources[0].status.phase is defined and tempostack_obc.resources[0].status.phase == 'Bound'
  retries: 12
  delay: 10 
- name: Get ODF ObjectBucketClaim Secret
  kubernetes.core.k8s_info:
    kind: Secret
    api_version: v1
    name: tempostack-obc
    namespace: tempo
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
  register: tempostack_obc_secret
- name: Get ODF ObjectBucketClaim Secret
  kubernetes.core.k8s_info:
    kind: ConfigMap
    api_version: v1
    name: tempostack-obc
    namespace: tempo
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
  register: tempostack_obc_cm
- set_fact:
    tempo_s3_endpoint: "https://{{ tempostack_obc_cm.resources[0].data.BUCKET_HOST }}"
    tempo_s3_bucket: "{{ tempostack_obc_cm.resources[0].data.BUCKET_NAME }}"
    tempo_s3_access_key_id: "{{ tempostack_obc_secret.resources[0].data.AWS_ACCESS_KEY_ID | b64decode }}"
    tempo_s3_access_key_secret: "{{  tempostack_obc_secret.resources[0].data.AWS_SECRET_ACCESS_KEY | b64decode }}"
- name: Create Tempo Secret
  redhat.openshift.k8s:
    template: tempo-secret.yaml.j2
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
- name: Create TempoStack
  redhat.openshift.k8s:
    src: tempostack.yaml
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
- name: Create TempoStack ClusterRoleBinding
  redhat.openshift.k8s:
    src: clusterrole-binding.yaml
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
