- name: Include OpenShift Common role
  include_role:
    name: openshift/common
    public: true
  when: openshift_token is undefined
- name: Create OpenShift OpenTelemetry namespace
  redhat.openshift.k8s:
    src: namespace.yaml
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
- name: Create OpenShift OpenTelemetry operator-group
  redhat.openshift.k8s:
    src: operator-group.yaml
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
- name: Create OpenShift OpenTelemetry subscription
  redhat.openshift.k8s:
    src: otel-sub.yaml
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
- name: Wait until OpenShift Tempo subscription is "Ready"
  kubernetes.core.k8s_info:
    kind: Subscription
    api_version: operators.coreos.com/v1alpha1
    name: otel
    namespace: openshift-opentelemetry-operator
    host: "{{ openshift_api_url }}"
    api_key: "{{ openshift_token }}"
    validate_certs: false
  register: otel_sub
  until: otel_sub.resources[0].status.state is defined and (otel_sub.resources[0].status.state == 'AtLatestKnown' or otel_sub.resources[0].status.state == 'UpgradeAvailable')
  retries: 12
  delay: 5
  ignore_errors: yes
