- name: Include OpenShift Common
  include_role:
    name: openshift/common
    public: true
- name: Execute pre-actions
  ansible.builtin.include_tasks:
    file: pre_actions.yaml
- name: Deploy Apicurio
  ansible.builtin.include_tasks:
    file: deploy_apicurio_registry.yaml
- name: Execute post-actions
  ansible.builtin.include_tasks:
    file: post_actions.yaml
