apiVersion: v1
kind: Service
metadata:
  name: postgres-ogx
  namespace: llm-hosting
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    gen-ai.opendatahub.io/pgvector: "true"
  sessionAffinity: None
  type: ClusterIP
