apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    gen-ai.opendatahub.io/pgvector: "true"
  name: ogx-pgvector-init
  namespace: llm-hosting
data:
  enable-pgvector.sh: |
    #!/bin/bash
    createdb ${POSTGRESQL_DATABASE}
    psql -c "alter user postgres with encrypted password 'postgres';"
    psql -c "grant all privileges on database ${POSTGRESQL_DATABASE} to postgres;"
    psql -U postgres -d "${POSTGRESQL_DATABASE}" -c "CREATE EXTENSION IF NOT EXISTS vector;"
